# Sonokai theme for Alacritty

[colors.primary]
foreground = "#e2e2e3" # fg
background = "#2c2e34" # bg0

[colors.normal]
black = "#181819"   # black
red = "#fc5d7c"     # red
green = "#9ed072"   # green
yellow = "#e7c664"  # yellow
blue = "#76cce0"    # blue
magenta = "#b39df3" # purple
cyan = "#8dd0b6"    # cyan
white = "#e2e2e3"   # fg

[colors.bright]
black = "#33353f"   # bg1
red = "#ff6077"     # bg_red
green = "#a7df78"   # bg_green
yellow = "#f39660"  # orange
blue = "#85d3f2"    # bg_blue
magenta = "#b39df3" # purple (same as normal for consistency)
cyan = "#8dd0b6"    # cyan (same as normal for consistency)
white = "#ffffff"   # bright white for high contrast

[colors.dim]
black = "#222327"   # bg_dim
red = "#55393d"     # diff_red
green = "#394634"   # diff_green
yellow = "#4e432f"  # diff_yellow
blue = "#354157"    # diff_blue
magenta = "#75617b" # slightly muted purple
cyan = "#5b7d78"    # muted cyan
white = "#7f8490"   # grey

[colors.hints]
start.foreground = "#2c2e34" # bg0
start.background = "#76cce0" # blue
end.foreground = "#76cce0"   # blue
end.background = "#2c2e34"   # bg0

[colors.search]
matches.foreground = "#000000"       # black
matches.background = "#e2e2e3"       # fg
focused_match.foreground = "#e2e2e3" # fg
focused_match.background = "#000000" # black
