import = ["~/.config/alacritty/gruvbox-dark.toml"]

[window]
padding = { x = 12, y = 12 }
dynamic_padding = true
title = "Alacritty"
startup_mode = "Maximized"
opacity = 0.9

[font]
normal = { family = "Cascadia Code", style = "Regular" }
size = 16
