general.import = ["./themes/gruvbox_material.toml"]

[window]
decorations = "none"
dynamic_padding = true

[font]
normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
size = 22

[keyboard]
bindings = [{ key = "N", mods = "Control|Shift", action = "ToggleFullscreen" }]
