import = ["~/.config/alacritty/gruvbox-dark.toml"]

[window]
padding = { x = 12, y = 12 }
dynamic_padding = true
title = "Alacritty"
startup_mode = "Maximized"
decorations = "none"
opacity = 0.97

[font]
normal = { family = "Mononoki Nerd Font", style = "Regular" }
size = 16
