theme = "sonokai"

[editor]
line-number = "relative"
true-color = true
cursorline = true
auto-format = true
mouse = false

[editor.soft-wrap]
enable = true

[keys.normal]
C-s = ":w!"
C-w = ":buffer-close"
y = [":clipboard-yank", "yank"]

[keys.insert]
C-s = [":w!", "normal_mode"]
C-w = [":buffer-close", "normal_mode"]

[keys.select]
y = [":clipboard-yank", "yank"]
