use-grammars = { only = ["c", "go", "lua", "python", "toml", "nix"] }

# C/C++
[[language]]
name = "c"
formatter = { command = "clang-format", args = [
  "--style={BasedOnStyle: Google}",
] }

[[language]]
name = "cpp"
formatter = { command = "clang-format", args = [
  "--style={BasedOnStyle: Google}",
] }

# TOML
[[language]]
name = "toml"
roots = ["."]

# NIX
[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }

# NIX
[[language]]
name = "go"
auto-format = true
formatter = { command = "gofmt" }
